CRUD_APP/CRUD_APP/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

CRUD_APP/core/urls.py
from django.urls import path
from . import views


app_name = 'core'
urlpatterns = [
  path(''                                 , views.view_CRUD_APP, name='show_CRUD'),
  path('<int:pk>'                                 , views.view_CRUD_APP, name='show_CRUD'),
  path('Edit/<str:table_or_data>/<int:pk>/', views.edit_table_or_data, name='edit'),
  path('Edit/<str:table_or_data>/', views.edit_table_or_data, name='edit'),
  path('delete/<str:table_or_data>/<int:pk>/', views.delete, name='delete'),
  path('Add/value/<int:pk>/', views.add_value, name='add_value'),
  path('Add/value/', views.add_value, name='add_value'),
  path('Add/table/', views.add_table, name='add_table'),
  # path("table/<int:pk>", views.view_table, name='show_table'),
]

CRUD_APP/core/models.py
from django.db import models



class Table(models.Model):
  name = models.CharField(max_length=20, default='')
  coulumn_header_1 = models.CharField(max_length=20, default='')
  coulumn_header_2 = models.CharField(max_length=20, default='')
  coulumn_header_3 = models.CharField(max_length=20, default='')
  coulumn_header_4 = models.CharField(max_length=20, default='')

  def __str__(self) -> str:
    return self.name


class DataInTable(models.Model):
  #4
  table_that_data_in = models.ForeignKey(Table, on_delete=models.CASCADE)
  coulumn1 = models.CharField(max_length=20, default='')
  coulumn2 = models.CharField(max_length=20, default='')
  coulumn3 = models.CharField(max_length=20, default='')
  coulumn4 = models.CharField(max_length=20, default='')
  
  def __str__(self):
    return str(self.table_that_data_in)

CRUD_APP/core/views.py
from django.shortcuts import render, redirect
from .models import DataInTable, Table
from django.http.request  import HttpRequest



def view_CRUD_APP(request, pk=None):
  
    if pk is not None:
      
      TABLES   = Table.objects.all() 
      TABLE    = Table.objects.get(pk=pk)
      DATA     = DataInTable.objects.filter(table_that_data_in=TABLE)
      var = {
        'data'     : DATA,
        'tables'   : TABLES,
        'table'    : TABLE,
      }
    else:
      table  = Table.objects.first()
      data = DataInTable.objects.filter(table_that_data_in=table)
      tables = Table.objects.all()
      print(table)
      var = {
        'table' : table,
        'data'  : data,
        'tables': tables
      }
    # print(TABLE.pk  ==  TABLES[0].pk)
    
    return render(request, 'core/show_values.html', var)



def edit_table_or_data(request, table_or_data, pk=None):
  if pk is None:
    return render(request, 'core/show_values.html')
  if request.method == 'POST':
    first = request.POST['first']
    second = request.POST['second']
    third = request.POST['third']
    fourth = request.POST['fourth']
    if table_or_data == 'table':
      table = Table.objects.get(pk=pk)
      table.coulumn_header_1 = first
      table.coulumn_header_2 = second
      table.coulumn_header_3 = third
      table.coulumn_header_4 = fourth
      table.save()
      return redirect('core:show_CRUD', f'{str(table.pk )}')
    elif table_or_data == 'data':
      first = request.POST['first']
      second = request.POST['second']
      third = request.POST['third']
      fourth = request.POST['fourth']
      
      item = DataInTable.objects.get(pk=pk)
      table = item.table_that_data_in
      
      item.coulumn1 = first
      item.coulumn2 = second
      item.coulumn3 = third
      item.coulumn4 = fourth
      item.save()
      return redirect('core:show_CRUD', f'{str(table.pk)}')
    
    
  else:
    if table_or_data == 'table':
      table = Table.objects.get(pk=pk)
      
      
      var = {
        'table' : table,
        'op'    : 'table'
      }
    elif table_or_data == 'data':
      the_data = DataInTable.objects.get(pk=pk)
      table    = the_data.table_that_data_in
      var      = {
        "table"    : table,
        'the_data' : the_data,
        'op'       : 'data',
        
        }
    return render(request, 'core/edit_value.html', var)

  # return render(request, )


# def view_table(request, pk):
#   pass

def delete(request, table_or_data,pk):
  if table_or_data == 'table':
    table = Table.objects.get(pk=pk)
    all_data = DataInTable.objects.filter(table_that_data_in=table)
    table.delete()
    all_data.delete()
    return redirect('core:show_CRUD')
    
  elif table_or_data == 'data':
    data = DataInTable.objects.get(pk=pk)
    data.delete()
    return redirect('core:show_CRUD')
  

def add_value(request:HttpRequest,pk=None):
  if pk is None:
    return render(request, 'core/show_values.html')
  table = Table.objects.get(pk=pk)
  
  if request.method == 'POST':
    first = request.POST['first']
    second = request.POST['second']
    third = request.POST['third']
    fourth = request.POST['fourth']
    item = DataInTable.objects.create(table_that_data_in=table, coulumn1=first, coulumn2=second, coulumn3=third, coulumn4=fourth)
    item.save
    
    return redirect('core:show_CRUD')
  else:
    var = {
      'table' : table,
      'op'    : 'add_value'
    }
    return render(request,'core/edit_value.html', var)

def add_table(request):
  
  
  if request.method == 'POST':
    name = request.POST['name']
    first = request.POST['first']
    second = request.POST['second']
    third = request.POST['third']
    fourth = request.POST['fourth']

    table = Table.objects.create(name=name, coulumn_header_1=first,
                        coulumn_header_2=second,
                        coulumn_header_3=third, 
                        coulumn_header_4=fourth
                        )
    table.save()
    return redirect('core:show_CRUD')
  else:
    var = {
      'op'    : 'add_table'
    }
    return render(request,'core/edit_value.html', var)

CRUD_APP/core/templates/core/edit_value.html
{% extends 'core/index.html' %}
{% load static %}



{% block title %}Edit_{{thing}}{% endblock title %}
{% block link %}<link rel="stylesheet" href="{% static 'css/edit_value.css' %}">{% endblock link %}

{% block content %}
  <section class="main">
  









    {% if op == 'table' %}
  <h1 style='color:white;'>{{table.name}}</h1>
  <form action="" method='post'>
    {% csrf_token %}  
      <label for="">First column</label>
      
      <textarea name="first" id="" cols="30" rows="10">{{table.coulumn_header_1}}</textarea>

      
      <label for="">Second column</label>
      <textarea name="second" id="" cols="30" rows="10">{{table.coulumn_header_2}}</textarea>


      <label for="">Third column</label>
      <textarea name="third" id="" cols="30" rows="10">{{table.coulumn_header_3}}</textarea>


      <label for="">Fourth column</label>
      <textarea name="fourth" id="" cols="30" rows="10">{{table.coulumn_header_4}}</textarea>

      











      {% elif op == 'data' %}
      <h1 style='color:white;'>{{table.name}} - {{the_data.coulumn1}} - {{the_data.coulumn2}}</h1>
  <form action="" method='post'>

    {% csrf_token %}
      <label for=""> {{table.coulumn_header_1}} </label>
      
      <textarea name="first" id="" cols="30" rows="10">{{the_data.coulumn1}}</textarea>

      
      <label for=""> {{table.coulumn_header_2}} </label>
      <textarea name="second" id="" cols="30" rows="10">{{ the_data.coulumn2}}</textarea>


      <label for=""> {{table.coulumn_header_3}} </label>
      <textarea name="third" id="" cols="30" rows="10">{{the_data.coulumn3}}</textarea>


      <label for="">  {{table.coulumn_header_4}}  </label>
      <textarea name="fourth" id="" cols="30" rows="10">{{the_data.coulumn4}}</textarea>

      













      {% elif op == 'add_value' %}
      <h1 style='color:white;'>{{table.name}} </h1>
  <form action="" method='post'>

    {% csrf_token %}
      <label for=""> {{table.coulumn_header_1}} </label>
      
      <textarea name="first" id="" cols="30" rows="10"></textarea>

      
      <label for=""> {{table.coulumn_header_2}} </label>
      <textarea name="second" id="" cols="30" rows="10"></textarea>


      <label for=""> {{table.coulumn_header_3}} </label>
      <textarea name="third" id="" cols="30" rows="10"></textarea>


      <label for="">  {{table.coulumn_header_4}}  </label>
      <textarea name="fourth" id="" cols="30" rows="10"></textarea>














      {% elif op == 'add_table' %}
      <h1 style='color:white;'>Add Table </h1>
  <form action="" method='post'>

    {% csrf_token %}
      <label for=""> table name </label>
      
      <textarea name="name" id="" cols="30" rows="10"></textarea>


      <label for=""> colmun 1 </label>
      
      <textarea name="first" id="" cols="30" rows="10"></textarea>

      
      <label for=""> colmun 2</label>
      <textarea name="second" id="" cols="30" rows="10"></textarea>


      <label for=""> colmun 3 </label>
      <textarea name="third" id="" cols="30" rows="10"></textarea>


      <label for="">  colmun 4 </label>
      <textarea name="fourth" id="" cols="30" rows="10"></textarea>

      {% endif %}
    <input type="submit" value="click">

  
  
  </form>
  
  
  
  
  
    <div class="icon">
      {% if op == 'table' %}
      
      <a href="{% url 'core:delete' 'table' table.pk %}"><i class="fa-regular fa-trash-can del"></i> </a>

      {% elif op == 'data'%}
      <a href="{% url 'core:delete' 'data' the_data.pk %}"><i class="fa-regular fa-trash-can del"></i> </a>
      {% endif %}
    <div class="night">
      <i class="fa-regular fa-moon"></i>
    </div>
    <div class="morning"> 
      <i class="fa-regular fa-sun"></i>
    </div>
    
    <div class="back"> 
      <a href='{% url "core:show_CRUD" %}'><i class="fa-solid fa-backward"></i></a>
        </div></div>
    
  </section>

  



  <script src="{% static 'js/edit_value.js' %}"></script>

  {% endblock content %}

CRUD_APP/core/templates/core/index.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %} </title>
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
  {% block link %}{% endblock link %}
</head>
<body>

    {% block content %}
    {% endblock content %}
</body>
</html>

CRUD_APP/core/templates/core/show_values.html
{% extends 'core/index.html' %}
{% load static %}

{% block title %}Show_Values{% endblock title %}
{% block link %}<link rel="stylesheet" href="{% static 'css/show_values.css' %}">
{% endblock link %}


{% block content %}
  <style>
    .main .header{
      grid-template-columns: repeat(20, 1fr);
    }
    .main .body{
      grid-template-columns: repeat(16,1fr);

    }
  </style>


  <section class="container">


    <div class="nav">
    <nav>

      {% for one_table in tables %}

      <a href="{% url 'core:show_CRUD' one_table.pk %}"  >
        <h2 {% if one_table.pk == table.pk %} class='selected' {% endif %} >{{one_table.name}}</h2>
      </a>

      {% endfor %}


    
    
    </nav>
    <div class="add-custom">
      <a href="{% url 'core:add_table' %}">
      <i class="fa-solid fa-plus add2"></i></a>
      <a {% if  table.pk != None %} href="{% url 'core:edit' 'table' table.pk  %}" {% else %}href="{% url 'core:show_CRUD'  %}{% endif %}">
      <i class="fa-solid fa-screwdriver-wrench screwdriver"></i>
      </a>
        </div>
  </div>
    <section class="main">
    <div class="header">
      <div class="header-row">ID</div>
      <div class="for-nothing"></div> 
      <div class="header-row">{{table.coulumn_header_1}}</div>
      <div class="for-nothing"></div>
      <div class="header-row">{{table.coulumn_header_2}}</div>
      <div class="for-nothing"></div>
      <div class="header-row">{{table.coulumn_header_3}} </div>
      <div class="for-nothing"></div>
      <div class="header-row"> {{ table.coulumn_header_4}} </div>
    
    </div>
<!--  fr = (x*2) -2  + x*2 + 2 -->
    <div class="body">

     
      {% for item in data %}
      <div class="body-row id"> {{ forloop.counter }} </div>
      <div class="body-row id icon">
        <a href="{% url 'core:delete' "data" item.pk %}"><i class="fa-regular fa-trash-can del"></i> </a>
        <a href="{% url 'core:edit' 'data' item.pk %}"> <i class="fa-regular fa-pen-to-square edit"></i></a>
      </div>
      <div class="body-row">{{item.coulumn1}}</div>
      <div class="for-nothing"></div>
      <div class="for-nothing"></div>
      <div class="body-row">{{item.coulumn2}}</div>
      <div class="for-nothing"></div>
      <div class="for-nothing"></div>
      <div class="body-row">{{item.coulumn3}}</div>
      <div class="for-nothing"></div>
      <div class="for-nothing"></div>
      <div class="body-row">{{item.coulumn4}}</div>
      {% endfor %}

      
  </div>



  </section>

  <div class="icons">
    <div class="right arrow">
      <i class="fa-solid fa-arrow-right"></i>
      
    </div>
    <div class="up arrow">
      <i class="fa-solid fa-angle-up"></i>
    </div>
    <a {% if table.pk == None %}href='{% url "core:add_value"  %}'{% else %}href='{% url "core:add_value" table.pk %}'{% endif %}  style='position:absolute;bottom:20px;right:100px'> 

      <i class="fa-solid fa-plus add2"></i></a>
    
    <div class="night">
      <i class="fa-regular fa-moon"></i>
    </div>
    <div class="morning"> 
      <i class="fa-regular fa-sun"></i>
      
    </div>  
    
    <div class="down arrow"> 
      <i class="fa-solid fa-angle-down"></i>
        </div>  

        <div class="left arrow">
          <i class="fa-solid fa-arrow-left"></i>
        </div>
        
  </div>
 
  
</section>

<script src="{% static 'js/show_values.js' %}"></script>
{% endblock content %}  